name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: sudo apt install golint
      
      - name: Run test suite
        run: make test
